# Generated by Django 3.1.2 on 2020-11-29 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_diaryy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryy',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
