# Generated by Django 3.1.2 on 2020-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201027_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryy',
            name='date',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
